import { NextResponse } from "next/server";
import type { z } from "zod";
import { unauthorizedAdmin, verifyAdmin } from "@/lib/admin-auth";
import {
  isEventConfigComplete,
  validateBossConfig,
  validateMerchantConfig,
} from "@/lib/event-config";
import { adminEventSchema, isParseError, parseBody } from "@/lib/schemas";
import { createAdminClient } from "@/lib/supabase-admin";

type AdminEventBody = z.infer<typeof adminEventSchema>;

/** List all events */
export async function GET(request: Request) {
  if (!verifyAdmin(request)) {
    return unauthorizedAdmin();
  }

  const admin = createAdminClient();
  const { data, error } = await admin
    .from("events")
    .select("*")
    .order("created_at", { ascending: false });

  if (error) {
    return NextResponse.json(
      { error: "Failed to fetch events" },
      { status: 500 },
    );
  }

  // Live HP for bosses, so the list shows how a fight is going and the edit
  // form starts from the real pool rather than the config copy.
  const bossIds = (data ?? [])
    .filter((e) => e.type === "boss_fight")
    .map((e) => e.id);
  const { data: states } = bossIds.length
    ? await admin
        .from("boss_state")
        .select("event_id, hp, max_hp, killed, escaped")
        .in("event_id", bossIds)
    : { data: [] };

  const events = (data ?? []).map((e) => {
    const state = states?.find((s) => s.event_id === e.id);
    return state
      ? {
          ...e,
          boss: {
            hp: state.hp,
            maxHp: state.max_hp,
            killed: state.killed,
            escaped: state.escaped,
          },
        }
      : e;
  });

  return NextResponse.json({ events });
}

/**
 * Create or update an event.
 *
 * Occurrences generated by a series (series_id set) are handled slightly
 * differently: any save marks them customized, so editing the series later
 * leaves them alone, and `active` is derived rather than taken from the form —
 * live exactly when not skipped and complete. That is what keeps an
 * uncurated song hunt or an unstocked George away from players.
 */
export async function POST(request: Request) {
  if (!verifyAdmin(request)) {
    return unauthorizedAdmin();
  }

  const body = await parseBody(request, adminEventSchema);
  if (isParseError(body)) return body;

  const { id, type, title, description, startsAt, endsAt } = body;
  let config = body.config ?? {};

  const admin = createAdminClient();

  let existing: {
    series_id: string | null;
    skipped: boolean;
    needs_approval: boolean;
  } | null = null;
  if (id) {
    const { data } = await admin
      .from("events")
      .select("series_id, skipped, needs_approval")
      .eq("id", id)
      .maybeSingle();
    existing = data;
  }
  const occurrence: Occurrence | null = existing?.series_id
    ? {
        skipped: body.skipped ?? existing.skipped,
        // A curator proposal stays held until the admin approves it — an
        // explicit approve, or saving the edit form (the admin curating it).
        needsApproval: existing.needs_approval && !body.approve,
      }
    : null;

  if (new Date(endsAt) <= new Date(startsAt)) {
    return badRequest("Event must end after it starts");
  }

  if (type === "boss_fight") {
    return saveBossFight(admin, body, occurrence);
  }

  if (type === "merchant") {
    const result = await validateMerchantConfig(admin, config);
    if ("error" in result) return badRequest(result.error);
    config = result.config;
  }

  // If an event has a rewardItemId, ensure the item exists in the items table
  if (config.rewardItemId) {
    const { data: existingItem } = await admin
      .from("items")
      .select("id")
      .eq("id", config.rewardItemId as string)
      .single();

    if (!existingItem) {
      // Auto-create the item entry
      await admin.from("items").insert({
        id: config.rewardItemId,
        name: (config.rewardItemName as string) ?? title,
        description:
          (config.rewardItemDescription as string) ?? `Reward for: ${title}`,
        rarity: (config.rewardItemRarity as string) ?? "legendary",
      });
    }
  }

  const row = {
    type,
    title,
    description: description ?? null,
    active: occurrence
      ? !occurrence.skipped &&
        !occurrence.needsApproval &&
        isEventConfigComplete(type, config)
      : (body.active ?? true),
    starts_at: startsAt,
    ends_at: endsAt,
    config,
    ...occurrenceColumns(occurrence),
  };

  if (id) {
    const { data, error } = await admin
      .from("events")
      .update(row)
      .eq("id", id)
      .select()
      .single();

    if (error) {
      return NextResponse.json(
        { error: "Failed to update event" },
        { status: 500 },
      );
    }
    return NextResponse.json({ event: data });
  }

  const { data, error } = await admin
    .from("events")
    .insert(row)
    .select()
    .single();

  if (error) {
    return NextResponse.json(
      { error: "Failed to create event" },
      { status: 500 },
    );
  }

  return NextResponse.json({ event: data }, { status: 201 });
}

/** Set when the event being saved was generated by a series. */
type Occurrence = { skipped: boolean; needsApproval: boolean };

function occurrenceColumns(occurrence: Occurrence | null) {
  return occurrence
    ? {
        skipped: occurrence.skipped,
        needs_approval: occurrence.needsApproval,
        customized: true,
      }
    : {};
}

/**
 * Create or update a boss_fight event.
 *
 * Separate from the generic path because a boss is two rows: the event, and a
 * boss_state row holding its HP. Without the second one sync_context never
 * reports the boss and deal_boss_damage drops every hit, so the event would
 * look live and be unkillable.
 */
async function saveBossFight(
  admin: ReturnType<typeof createAdminClient>,
  body: AdminEventBody,
  occurrence: Occurrence | null,
) {
  const { id, title, description, startsAt, endsAt } = body;
  const active = occurrence ? !occurrence.skipped : (body.active ?? true);

  const result = await validateBossConfig(admin, body.config ?? {});
  if ("error" in result) return badRequest(result.error);
  const config = result.config;
  const maxHp = config.maxHp as number;

  // At most one boss at a time: sync_context picks "the" active boss.
  if (active) {
    let overlap = admin
      .from("events")
      .select("id, title")
      .eq("type", "boss_fight")
      .eq("active", true)
      .lt("starts_at", endsAt)
      .gt("ends_at", startsAt);
    if (id) overlap = overlap.neq("id", id);
    const { data: clash } = await overlap.limit(1);
    if (clash && clash.length > 0) {
      return NextResponse.json(
        { error: `Overlaps another boss fight: "${clash[0].title}"` },
        { status: 409 },
      );
    }
  }

  const row = {
    type: "boss_fight",
    title,
    description: description ?? null,
    active,
    starts_at: startsAt,
    ends_at: endsAt,
    config,
    ...occurrenceColumns(occurrence),
  };

  if (id) {
    // HP first: it is the half that can be refused (boss already dead, or the
    // new pool is smaller than the damage already dealt).
    const { error: hpError } = await admin.rpc("admin_set_boss_hp", {
      p_event_id: id,
      p_max_hp: maxHp,
    });
    if (hpError) return badRequest(hpError.message);

    const { data, error } = await admin
      .from("events")
      .update(row)
      .eq("id", id)
      .select()
      .single();
    if (error) {
      return NextResponse.json(
        { error: "Failed to update event" },
        { status: 500 },
      );
    }
    return NextResponse.json({ event: data });
  }

  const { data, error } = await admin
    .from("events")
    .insert(row)
    .select()
    .single();
  if (error || !data) {
    return NextResponse.json(
      { error: "Failed to create event" },
      { status: 500 },
    );
  }

  const { error: hpError } = await admin.rpc("admin_set_boss_hp", {
    p_event_id: data.id,
    p_max_hp: maxHp,
  });
  if (hpError) {
    // Don't leave a boss with no HP pool behind.
    await admin.from("events").delete().eq("id", data.id);
    return badRequest(hpError.message);
  }

  return NextResponse.json({ event: data }, { status: 201 });
}

function badRequest(error: string) {
  return NextResponse.json({ error }, { status: 400 });
}

/** Delete an event */
export async function DELETE(request: Request) {
  if (!verifyAdmin(request)) {
    return unauthorizedAdmin();
  }

  const { searchParams } = new URL(request.url);
  const id = searchParams.get("id");

  if (!id) {
    return NextResponse.json(
      { error: "id query param is required" },
      { status: 400 },
    );
  }

  const admin = createAdminClient();
  const { error } = await admin.from("events").delete().eq("id", id);

  if (error) {
    return NextResponse.json(
      { error: "Failed to delete event" },
      { status: 500 },
    );
  }

  return NextResponse.json({ ok: true });
}
