#!/usr/bin/env node
/**
 * Regenerates the copy of the shared game rules that the Supabase edge
 * functions compile against.
 *
 * WHY A COPY AT ALL: `supabase functions deploy` only uploads files under
 * `supabase/`, so the functions cannot import `../../packages/shared`. The
 * copy used to be a hand-written 497-line transcription that drifted from the
 * real package and carried its own manually-maintained item-id list. It is now
 * a build artifact: generated from `packages/shared/src/game-rules.ts`,
 * committed so deploys need no extra tooling, and checked in CI.
 *
 * HOW: walks the import graph from the entry point, copies every reachable
 * file verbatim, and rewrites relative specifiers from `./x.js` (the NodeNext
 * style the package uses) to `./x.ts` (which is what Deno resolves). No
 * bundler, so type declarations survive and the output stays diffable against
 * the originals.
 *
 * A file that reaches outside the graph — React, the DOM, a Node built-in —
 * will fail `deno check` on the functions, which is the intended alarm.
 *
 *   node scripts/vendor-shared.mjs          regenerate
 *   node scripts/vendor-shared.mjs --check  exit 1 if the committed copy is stale
 */
import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const OUT_DIR = join(ROOT, "supabase/functions/_shared/shared");

/**
 * What the edge functions compile against, and everything reachable from it.
 *
 * `game-events.ts` is listed explicitly because nothing in the other two
 * imports it — `game-server.ts` defines its own secret-track matching, and
 * `buildSongHuntConfig` is only reached from the events-active function. Drop
 * it from this list and that function stops compiling.
 */
const ENTRIES = [
  join(ROOT, "packages/shared/src/game-rules.ts"),
  join(ROOT, "packages/shared/src/game-server.ts"),
  join(ROOT, "packages/shared/src/game-events.ts"),
];

const BANNED = [
  // Anything that would make the output non-portable to Deno. Checked against
  // import specifiers, not free text, so a comment mentioning React is fine.
  { test: /^react/, why: "React" },
  { test: /^node:/, why: "a Node built-in" },
  { test: /^next\//, why: "Next.js" },
];

/** Relative import specifiers in a module, in source order. */
function importsOf(source) {
  const specifiers = [];
  const patterns = [
    /\bfrom\s+["']([^"']+)["']/g,
    /\bimport\s+["']([^"']+)["']/g,
    /\bexport\s+\*\s+from\s+["']([^"']+)["']/g,
  ];
  for (const re of patterns) {
    for (const m of source.matchAll(re)) specifiers.push(m[1]);
  }
  return specifiers;
}

function collect(entries) {
  const files = new Map();
  const queue = [...entries];

  while (queue.length > 0) {
    const file = queue.shift();
    if (files.has(file)) continue;
    if (!existsSync(file)) {
      throw new Error(`vendor-shared: cannot resolve ${relative(ROOT, file)}`);
    }
    const source = readFileSync(file, "utf8");
    files.set(file, source);

    for (const spec of importsOf(source)) {
      for (const { test, why } of BANNED) {
        if (test.test(spec)) {
          throw new Error(
            `vendor-shared: ${relative(ROOT, file)} imports ${why} ("${spec}").\n` +
              `The edge functions cannot run that. Move whatever needs it out of the ` +
              `game-rules.ts import graph.`,
          );
        }
      }
      if (!spec.startsWith(".")) continue; // bare specifiers are left alone
      queue.push(resolve(dirname(file), spec.replace(/\.js$/, ".ts")));
    }
  }
  return files;
}

/** Rewrite `./x.js` -> `./x.ts` so Deno can resolve the copied files. */
function forDeno(source, name) {
  const rewritten = source.replace(
    /(\bfrom\s+["']|\bimport\s+["'])(\.[^"']*?)\.js(["'])/g,
    (_m, lead, path, quote) => `${lead}${path}.ts${quote}`,
  );
  return (
    `// @generated by scripts/vendor-shared.mjs — DO NOT EDIT.\n` +
    `// Source: packages/shared/src/${name}\n` +
    `// Run \`pnpm vendor:shared\` after changing the original.\n` +
    `\n${rewritten}`
  );
}

const collected = collect(ENTRIES);
const generated = new Map();
for (const [file, source] of collected) {
  const name = relative(join(ROOT, "packages/shared/src"), file);
  generated.set(name.replace(/\.ts$/, ".ts"), forDeno(source, name));
}

const check = process.argv.includes("--check");

if (check) {
  const stale = [];
  const existing = existsSync(OUT_DIR)
    ? readdirSync(OUT_DIR).filter((f) => f.endsWith(".ts"))
    : [];
  for (const [name, content] of generated) {
    const path = join(OUT_DIR, name);
    if (!existsSync(path) || readFileSync(path, "utf8") !== content) {
      stale.push(name);
    }
  }
  for (const name of existing) {
    if (!generated.has(name)) stale.push(`${name} (no longer generated)`);
  }
  if (stale.length > 0) {
    console.error(
      `The vendored shared game rules are out of date:\n` +
        stale.map((s) => `  - ${s}`).join("\n") +
        `\n\nRun \`pnpm vendor:shared\` and commit the result.`,
    );
    process.exit(1);
  }
  console.log(`vendor-shared: up to date (${generated.size} files)`);
} else {
  rmSync(OUT_DIR, { recursive: true, force: true });
  mkdirSync(OUT_DIR, { recursive: true });
  for (const [name, content] of generated) {
    writeFileSync(join(OUT_DIR, name), content);
  }
  console.log(
    `vendor-shared: wrote ${generated.size} files to ${relative(ROOT, OUT_DIR)}`,
  );
  for (const name of [...generated.keys()].sort()) console.log(`  ${name}`);
}
