// @generated by scripts/vendor-shared.mjs — DO NOT EDIT.
// Source: packages/shared/src/ascii3d.ts
// Run `pnpm vendor:shared` after changing the original.

/**
 * Shared 3D math, types, and constants for ASCII renderers.
 */

export type V3 = [number, number, number];
export type V2 = [number, number];

export function rotX(p: V3, a: number): V3 {
  const c = Math.cos(a),
    s = Math.sin(a);
  return [p[0], p[1] * c - p[2] * s, p[1] * s + p[2] * c];
}

export function rotY(p: V3, a: number): V3 {
  const c = Math.cos(a),
    s = Math.sin(a);
  return [p[0] * c + p[2] * s, p[1], -p[0] * s + p[2] * c];
}

export function rotZ(p: V3, a: number): V3 {
  const c = Math.cos(a),
    s = Math.sin(a);
  return [p[0] * c - p[1] * s, p[0] * s + p[1] * c, p[2]];
}

export function dot3(a: V3, b: V3): number {
  return a[0] * b[0] + a[1] * b[1] + a[2] * b[2];
}

export function normV(v: V3): V3 {
  const l = Math.sqrt(v[0] * v[0] + v[1] * v[1] + v[2] * v[2]);
  return [v[0] / l, v[1] / l, v[2] / l];
}

export function cross(a: V3, b: V3): V3 {
  return [
    a[1] * b[2] - a[2] * b[1],
    a[2] * b[0] - a[0] * b[2],
    a[0] * b[1] - a[1] * b[0],
  ];
}

export function col(hex: string, ch: string): string {
  return `<span style="color:${hex}">${ch}</span>`;
}

export const RAMP_HERZIE = "▓";
export const RAMP_ITEM = " .·:;=+*#%@█";
export const LIGHT = normV([0.4, -0.6, -0.8]);
export const CHAR_ASPECT = 2.1;

/**
 * Canonical rainbow ramp. Shared by the Prism colour scheme, its inventory
 * card, and the Rainbow Headband so all three show the same seven hues.
 */
export const RAINBOW_RAMP = [
  "#FF6B6B",
  "#FFA94D",
  "#FFD43B",
  "#69DB7C",
  "#4DABF7",
  "#9775FA",
  "#F783AC",
] as const;

/**
 * Ocean-blue ramp for the Poseidon's Gift colour scheme, shared by the
 * creature renderer's colour scheme and this item's inventory card.
 */
export const OCEAN_RAMP = [
  "#BFEFFF",
  "#7EC8E3",
  "#4AA8D8",
  "#2E86C1",
  "#1B5FA8",
  "#123F7A",
] as const;

/**
 * Violet ramp for the Purple Dane colour scheme. Built around
 * CREATURE_PALETTE's "soft violet" (#C3A6FF) — the skin exists to paint a
 * herzie a colour it could already have hatched with, so the ramp keeps that
 * exact hue (259.6°) and only walks lightness across OCEAN_RAMP's span,
 * easing saturation down at the dark end so shadows don't read as neon.
 */
export const VIOLET_RAMP = [
  "#DDCCFF",
  "#B28EFC",
  "#8953F7",
  "#601BEF",
  "#4812B8",
  "#320F7B",
] as const;

/**
 * Teal ramp for the Thanks for all the fish! colour scheme. Same construction
 * as VIOLET_RAMP, around CREATURE_PALETTE's "teal" (#4ECDC4, hue 175.7°).
 */
export const TEAL_RAMP = [
  "#6ED6CF",
  "#54CBC3",
  "#3DBCB3",
  "#379E96",
  "#2F807A",
  "#27635F",
] as const;

/**
 * Boss ramp — the only ramp that is not built around a CREATURE_PALETTE hue,
 * because a boss is deliberately not a colour a herzie could hatch with.
 *
 * Runs ember-red at the top to near-black at the bottom, which is the inverse
 * of every other ramp here: those brighten downward, this one swallows the
 * legs. RAMP_HERZIE is a single glyph, so the sink into black is the only way
 * the silhouette can lose its own feet.
 */
export const VOID_RAMP = [
  "#C8341B",
  "#93220F",
  "#63150A",
  "#3D0C06",
  "#220604",
  "#0E0202",
] as const;
