// @generated by scripts/vendor-shared.mjs — DO NOT EDIT.
// Source: packages/shared/src/game-events.ts
// Run `pnpm vendor:shared` after changing the original.

/**
 * Song-hunt and secret-track event logic, shared by the Next.js API and the
 * Supabase edge functions.
 *
 * Canonical source. `scripts/vendor-shared.mjs` regenerates the edge copy from
 * this file; `packages/web/src/lib/events.ts` re-exports it. Keep it free of
 * Node and Deno APIs — see game-rules.ts for why.
 */
import type { SupabaseClient } from "@supabase/supabase-js";
import type {
  BossDamageDealer,
  BossFightConfig,
  SongHuntConfig,
  SongHuntFinder,
} from "./game-rules.ts";

function garbleText(text: string, seed: string): string {
  let h = 0;
  for (let i = 0; i < seed.length; i++) {
    h = ((h << 5) - h + seed.charCodeAt(i)) | 0;
  }
  const chars = "abcdefghijklmnopqrstuvwxyz0123456789";
  return text
    .split("")
    .map((ch) => {
      if (ch === " ") return " ";
      h = (h * 1103515245 + 12345) | 0;
      return chars[Math.abs(h) % chars.length];
    })
    .join("");
}

const MAX_HINT_AUDIO_PLAYS = 3;

export async function buildSongHuntConfig(
  admin: SupabaseClient,
  eventId: string,
  config: SongHuntConfig,
  now: Date,
  includeTrackInfo: boolean = false,
  userId: string | null = null,
): Promise<Record<string, unknown>> {
  const unlockedAudioKeys = config.hints
    .filter((h) => h.audioKey && now >= new Date(h.unlocksAt))
    .map((h) => h.audioKey as string);

  let playCounts = new Map<string, number>();
  if (userId && unlockedAudioKeys.length > 0) {
    const { data: plays } = await admin
      .from("hint_plays")
      .select("audio_key, play_count")
      .eq("user_id", userId)
      .in("audio_key", unlockedAudioKeys);
    playCounts = new Map(
      (plays ?? []).map((p) => [p.audio_key as string, p.play_count as number]),
    );
  }

  const hints = config.hints.map((hint, i) => {
    const unlocked = now >= new Date(hint.unlocksAt);
    const result: Record<string, unknown> = {
      text: unlocked ? hint.text : garbleText(hint.text, `${eventId}${i}`),
      unlocksAt: hint.unlocksAt,
      unlocked,
    };
    // Locked hints never carry audio metadata — same principle as garbling
    // the text: nothing about a locked hint should be inspectable.
    if (unlocked && hint.audioKey) {
      result.hasAudio = true;
      if (userId) {
        const playCount = playCounts.get(hint.audioKey) ?? 0;
        result.playsRemaining = Math.max(0, MAX_HINT_AUDIO_PLAYS - playCount);
      }
    }
    return result;
  });

  const { data: claims } = await admin
    .from("event_claims")
    .select("claimed_at, user_id")
    .eq("event_id", eventId)
    .order("claimed_at", { ascending: true })
    .limit(config.maxClaims);

  let firstFinders: SongHuntFinder[] = [];
  if (claims && claims.length > 0) {
    const userIds = claims.map((c) => c.user_id as string);
    const { data: herzies } = await admin
      .from("herzies")
      .select("user_id, name")
      .in("user_id", userIds);

    const nameMap = new Map(
      (herzies ?? []).map((h) => [h.user_id, h.name as string]),
    );
    firstFinders = claims.map((c) => ({
      name: nameMap.get(c.user_id as string) ?? "Unknown",
      claimedAt: c.claimed_at as string,
    }));
  }

  const result: Record<string, unknown> = {
    rewardItemId: config.rewardItemId,
    maxClaims: config.maxClaims,
    hints,
    firstFinders,
  };

  if (includeTrackInfo) {
    result.trackTitle = config.trackTitle;
    result.trackArtist = config.trackArtist;
  }

  return result;
}

/**
 * Project a boss_fight event for a client.
 *
 * Live HP and the leaderboard live in `boss_state` / `boss_damage`, both of
 * which have SELECT revoked from anon and authenticated (00073, same posture
 * as the events lockdown in 00016). Everything a client sees about a boss
 * comes through here, on the service-role client.
 */
export async function buildBossFightConfig(
  admin: SupabaseClient,
  eventId: string,
  config: BossFightConfig,
  userId: string | null = null,
  topCount: number = 3,
): Promise<Record<string, unknown>> {
  const { data: state } = await admin
    .from("boss_state")
    .select("hp, max_hp, killed, escaped")
    .eq("event_id", eventId)
    .maybeSingle();

  const { data: board } = await admin.rpc("boss_leaderboard", {
    p_event_id: eventId,
    p_limit: topCount,
  });

  const topDealers: BossDamageDealer[] = (
    (board ?? []) as { name: string; damage: number; rank: number }[]
  ).map((r) => ({
    name: r.name ?? "Unknown",
    damage: Math.round(r.damage),
    rank: Number(r.rank),
  }));

  // The caller's own damage is a separate read: they are very often not in
  // the top N, and "you: 64" is the line that makes the board feel personal.
  let yourDamage = 0;
  let yourRank: number | null = null;
  if (userId) {
    const { data: mine } = await admin
      .from("boss_damage")
      .select("damage")
      .eq("event_id", eventId)
      .eq("user_id", userId)
      .maybeSingle();
    yourDamage = Math.round((mine?.damage as number) ?? 0);

    if (yourDamage > 0) {
      const { count } = await admin
        .from("boss_damage")
        .select("user_id", { count: "exact", head: true })
        .eq("event_id", eventId)
        .gt("damage", (mine?.damage as number) ?? 0);
      yourRank = (count ?? 0) + 1;
    }
  }

  const killed = state?.killed ?? false;

  return {
    hatedGenres: config.hatedGenres ?? [],
    // The reward is a mystery until the boss is down, and it is withheld
    // SERVER-SIDE rather than merely hidden by the UI — clients cannot read
    // `events` directly (00016), but anything projected into config is
    // inspectable in the response. This is the same reasoning that makes
    // buildSongHuntConfig garble locked hints instead of trusting the client
    // not to look.
    rewardItemId: killed ? config.rewardItemId : undefined,
    topRewardItemId: killed ? config.topRewardItemId : undefined,
    topCount: config.topCount ?? 3,
    hp: state?.hp ?? 0,
    maxHp: state?.max_hp ?? config.maxHp ?? 0,
    killed,
    escaped: state?.escaped ?? false,
    topDealers,
    yourDamage,
    yourRank,
  };
}
