// @generated by scripts/vendor-shared.mjs — DO NOT EDIT.
// Source: packages/shared/src/items.ts
// Run `pnpm vendor:shared` after changing the original.

/**
 * Item definitions with 3D ASCII art renderer.
 * Ported from CLI — uses HTML color spans instead of chalk.
 */

// Imported from the leaf module rather than the package barrel: the barrel
// re-exports this file, and that cycle left RAINBOW_RAMP undefined while the
// item frames were being generated at module load.
import {
  CHAR_ASPECT,
  col,
  cross,
  dot3,
  LIGHT,
  normV,
  OCEAN_RAMP,
  RAINBOW_RAMP,
  RAMP_ITEM,
  rotY,
  rotZ,
  type V2,
  type V3,
} from "./ascii3d.ts";

export type Rarity = "common" | "uncommon" | "rare" | "legendary";

/** Inventory grouping. Most items are cards (some grant a visual, some a bonus); "misc" is for non-card items. */
export type ItemCategory = "deck" | "misc";

/** Catalog equip categories (item.equip_slot). Ground items choose a side at equip time.
 * "modifier" stacks up to MAX_MODIFIERS — see EQUIPPED_SLOTS below, it isn't one of the
 * single-value slots. */
export const EQUIP_SLOTS = [
  "head",
  "face",
  "body",
  "scenery",
  "ground",
  "color",
  "modifier",
] as const;
export type EquipSlot = (typeof EQUIP_SLOTS)[number];

/** Single-value keys stored on herzies.equipped — ground splits into left/right instance
 * slots. Modifier items are tracked separately via the `modifier` array on Equipped, since
 * any number of them can be equipped at once (see Equipped below). */
export const EQUIPPED_SLOTS = [
  "head",
  "face",
  "body",
  "scenery",
  "ground_left",
  "ground_right",
  "color",
] as const;
export type EquippedSlot = (typeof EQUIPPED_SLOTS)[number];

/** Modifier items stack in Equipped.modifier, but only up to this many at once
 * (enforced server-side in the equip route; the desktop UI also disables the
 * Equip action once this cap is hit, for instant feedback). */
export const MAX_MODIFIERS = 6;

export type GroundSide = "left" | "right";

/** Slot-keyed map of currently equipped item IDs. `modifier` is a list (up to
 * MAX_MODIFIERS) rather than a single-value slot, since more than one modifier
 * item can be equipped at once. */
export type Equipped = Partial<Record<EquippedSlot, string>> & {
  modifier?: string[];
};

export function groundSlot(side: GroundSide): EquippedSlot {
  return side === "left" ? "ground_left" : "ground_right";
}

export function equippedItemIds(
  equipped: Equipped | null | undefined,
): string[] {
  if (!equipped) return [];
  const single = Object.values(equipped).filter(
    (id): id is string => typeof id === "string" && id.length > 0,
  );
  return [...single, ...(equipped.modifier ?? [])];
}

export function findEquippedSlot(
  equipped: Equipped | null | undefined,
  itemId: string,
): EquippedSlot | null {
  if (!equipped) return null;
  for (const slot of EQUIPPED_SLOTS) {
    if (equipped[slot] === itemId) return slot;
  }
  return null;
}

export function isModifierEquipped(
  equipped: Equipped | null | undefined,
  itemId: string,
): boolean {
  return !!equipped?.modifier?.includes(itemId);
}

/** Fixed bank capacity in the desktop Cards grid (6×3 — see InventoryView's
 * GRID_COLS/GRID_ROWS, which must stay in sync with this). Exported here so
 * non-UI code (e.g. deciding whether to warn before a purchase or pickup)
 * doesn't have to duplicate the slot-counting rules below. */
export const BANK_SLOT_COUNT = 18;

/** The only two item facts bank-slot counting needs. */
export interface BankItemInfo {
  stackable?: boolean;
  category: ItemCategory;
}

/**
 * Resolves those facts for an item id. Defaults to the bundled catalog; server
 * code that has no catalog (the Edge Functions) passes one built from the
 * `items` table instead, so there is one slot-counting implementation rather
 * than a second one to keep in sync.
 */
export type BankItemLookup = (itemId: string) => BankItemInfo | undefined;

const catalogBankLookup: BankItemLookup = (itemId) => {
  const item = getItem(itemId);
  if (!item) return undefined;
  return { stackable: item.stackable, category: getItemCategory(item) };
};

/** How many of the fixed bank slots (see BANK_SLOT_COUNT) `inventory`
 * currently needs: one slot per stackable item id owned (any quantity),
 * plus one per unit of a non-stackable item — except whatever's currently
 * equipped, which reserves a unit as "worn" and frees its bank slot. Mirrors
 * the slot-key expansion InventoryView uses to lay out its grid. */
export function bankSlotsUsed(
  inventory: Record<string, number> | null | undefined,
  equipped: Equipped | null | undefined,
  lookup: BankItemLookup = catalogBankLookup,
): number {
  if (!inventory) return 0;
  let count = 0;
  for (const [itemId, qty] of Object.entries(inventory)) {
    if (qty <= 0) continue;
    const item = lookup(itemId);
    if (item && item.category !== "deck") continue;
    const isEquipped =
      findEquippedSlot(equipped, itemId) !== null ||
      isModifierEquipped(equipped, itemId);
    if (item?.stackable) {
      if (!isEquipped) count += 1;
      continue;
    }
    count += Math.max(0, isEquipped ? qty - 1 : qty);
  }
  return count;
}

/** Whether the bank has no free slot left for a fresh item — see
 * bankSlotsUsed. */
export function isBankFull(
  inventory: Record<string, number> | null | undefined,
  equipped: Equipped | null | undefined,
  lookup: BankItemLookup = catalogBankLookup,
): boolean {
  return bankSlotsUsed(inventory, equipped, lookup) >= BANK_SLOT_COUNT;
}

/**
 * Whether one more of `itemId` would fit in the bank.
 *
 * Not the same question as `isBankFull`: a stackable item the player already
 * owns shares its existing slot, so it still fits at capacity. Gate item
 * *acquisition* on this rather than on `isBankFull`, or a full bank wrongly
 * blocks picking up another copy of something already stacked there.
 *
 * Pass a `lookup` to source item facts from somewhere other than the bundled
 * catalog — server code can build one from the `items` table.
 */
export function hasRoomFor(
  inventory: Record<string, number> | null | undefined,
  equipped: Equipped | null | undefined,
  itemId: string,
  lookup: BankItemLookup = catalogBankLookup,
): boolean {
  const current = inventory ?? {};
  const next = { ...current, [itemId]: (current[itemId] ?? 0) + 1 };
  return bankSlotsUsed(next, equipped, lookup) <= BANK_SLOT_COUNT;
}

/** Normalize API/cache payloads that may still be a legacy string[]. */
export function normalizeEquipped(raw: unknown): Equipped {
  if (!raw || typeof raw !== "object") return {};
  if (Array.isArray(raw)) {
    // Legacy array — drop side info; callers should re-equip after migration.
    return {};
  }
  const out: Equipped = {};
  for (const slot of EQUIPPED_SLOTS) {
    const v = (raw as Record<string, unknown>)[slot];
    if (typeof v === "string" && v.length > 0) out[slot] = v;
  }
  const modifierRaw = (raw as Record<string, unknown>).modifier;
  if (Array.isArray(modifierRaw)) {
    const ids = modifierRaw.filter(
      (id): id is string => typeof id === "string" && id.length > 0,
    );
    if (ids.length > 0) out.modifier = ids;
  } else if (typeof modifierRaw === "string" && modifierRaw.length > 0) {
    out.modifier = [modifierRaw];
  }
  return out;
}

/** Why an equip/unequip can't be applied to a given Equipped. Ownership and
 * "is this item even equipable" aren't here — they need the inventory/catalog
 * the caller holds, and stay the caller's job (see the equip route). */
export type EquipRejection =
  | "already-equipped"
  | "not-equipped"
  | "max-modifiers"
  | "missing-side"
  | "no-slot";

export type EquipOutcome =
  | { ok: true; equipped: Equipped }
  | { ok: false; reason: EquipRejection };

/**
 * The single source of truth for what equipping or unequipping does to
 * `Equipped`. The server applies it to persist the change and the desktop
 * client applies it to predict the result optimistically — sharing one
 * function is what lets the optimistic state match the server's byte for byte,
 * so the real response lands as a no-op instead of a visible correction.
 *
 * Pure: never mutates `current`. `equipSlot` is passed in rather than looked up
 * because the server reads it from the DB row (`equip_slot`) and the client
 * from the bundled catalog (`getItem(...).equipSlot`).
 *
 * Note that equipping into an occupied single-value slot **displaces** the
 * incumbent rather than refusing — that's deliberate (swapping a hat shouldn't
 * need an explicit unequip first), and the displaced item returns to the bank.
 */
export function applyEquip(
  current: Equipped,
  itemId: string,
  action: "equip" | "unequip",
  equipSlot: EquipSlot | undefined,
  side?: GroundSide,
): EquipOutcome {
  const isEquipped =
    findEquippedSlot(current, itemId) !== null ||
    isModifierEquipped(current, itemId);

  if (action === "unequip") {
    if (!isEquipped) return { ok: false, reason: "not-equipped" };
    const equipped: Equipped = { ...current };
    const slot = findEquippedSlot(current, itemId);
    if (slot) {
      delete equipped[slot];
    } else {
      const rest = (current.modifier ?? []).filter((id) => id !== itemId);
      if (rest.length > 0) equipped.modifier = rest;
      else delete equipped.modifier;
    }
    return { ok: true, equipped };
  }

  if (isEquipped) return { ok: false, reason: "already-equipped" };

  const equipped: Equipped = { ...current };

  if (equipSlot === "ground") {
    if (side !== "left" && side !== "right") {
      return { ok: false, reason: "missing-side" };
    }
    equipped[groundSlot(side)] = itemId;
    return { ok: true, equipped };
  }

  if (equipSlot === "modifier") {
    const worn = current.modifier ?? [];
    if (worn.length >= MAX_MODIFIERS) {
      return { ok: false, reason: "max-modifiers" };
    }
    equipped.modifier = [...worn, itemId];
    return { ok: true, equipped };
  }

  if (!equipSlot) return { ok: false, reason: "no-slot" };

  // Single-value slot — displaces whatever was worn there. No cast needed:
  // ruling out "ground" and "modifier" above narrows EquipSlot to exactly the
  // members EquippedSlot also has.
  equipped[equipSlot] = itemId;
  return { ok: true, equipped };
}

export type SellRejection = "not-sellable" | "not-enough";

export type SellOutcome =
  | {
      ok: true;
      /** Inventory with the sold units removed (the id is dropped at zero). */
      inventory: Record<string, number>;
      earned: number;
      newCurrency: number;
      /** Equip state after the sale — see the unequip note below. */
      equipped: Equipped;
      /** True when selling the last copy forced an unequip. */
      unequipped: boolean;
    }
  | { ok: false; reason: SellRejection };

/**
 * The single source of truth for what selling does. Server-side this computes
 * the row to persist; client-side it predicts the result so the grid and coin
 * move on click instead of after the round trip. Sharing one function is what
 * keeps the prediction identical to what the server will store.
 *
 * Pure: never mutates `inventory` or `equipped`.
 *
 * Selling the last copy of an equipped item unequips it in the same operation —
 * ownership and equip state must never drift apart, and an item you no longer
 * own can't stay worn.
 */
export function applySell(
  inventory: Record<string, number>,
  currency: number,
  equipped: Equipped,
  itemId: string,
  quantity: number,
  sellPrice: number | undefined,
): SellOutcome {
  if (!sellPrice) return { ok: false, reason: "not-sellable" };

  const owned = inventory[itemId] ?? 0;
  if (owned < quantity) return { ok: false, reason: "not-enough" };

  const nextInventory = { ...inventory };
  const newQty = owned - quantity;
  let nextEquipped = equipped;
  let unequipped = false;

  if (newQty > 0) {
    nextInventory[itemId] = newQty;
  } else {
    delete nextInventory[itemId];
    // No copies left — it can't remain equipped. Reuses applyEquip's unequip
    // branch so this agrees with an explicit unequip exactly.
    const removal = applyEquip(equipped, itemId, "unequip", undefined);
    if (removal.ok) {
      nextEquipped = removal.equipped;
      unequipped = true;
    }
  }

  const earned = quantity * sellPrice;
  return {
    ok: true,
    inventory: nextInventory,
    earned,
    newCurrency: currency + earned,
    equipped: nextEquipped,
    unequipped,
  };
}

export interface ItemDef {
  id: string;
  name: string;
  description: string;
  rarity: Rarity;
  frames: string[][]; // Each frame is an array of lines (with HTML color spans)
  /** Whether owning more than one is allowed (gates re-buying from the
   * store). For now, artefacts — items with no equipSlot/equipable, see
   * getItemType — are the only stackable item type. */
  stackable?: boolean;
  equipable?: boolean;
  /** Catalog category; ground items occupy ground_left or ground_right when equipped,
   * modifier items stack unbounded in Equipped.modifier. */
  equipSlot?: EquipSlot;
  sellPrice?: number;
  /** Set when the item can be bought with in-game currency from the store's Items tab. */
  buyPrice?: number;
  /** Inventory sub-tab grouping. Defaults to "deck" when unset. */
  category?: ItemCategory;
  /** Set when the item has a gameplay effect while equipped (e.g. an XP bonus), not just cosmetic. */
  modifier?: {
    /** Short label for the effect badge, e.g. "Exp boost". */
    label: string;
    /** Hover detail, e.g. "2% per song hunt won". */
    tooltip: string;
  };
}

export function getItemCategory(item: Pick<ItemDef, "category">): ItemCategory {
  return item.category ?? "deck";
}

/** Display classification, derived from the equip fields rather than stored directly. */
export type ItemType =
  | "skin"
  | "sceneryCard"
  | "equipable"
  | "accessory"
  | "modifier"
  | "artefact";

export function getItemType(
  item: Pick<ItemDef, "equipable" | "equipSlot" | "modifier">,
): ItemType {
  if (item.equipSlot === "color") return "skin";
  if (item.equipSlot === "modifier") return "modifier";
  if (item.equipSlot === "scenery") return "sceneryCard";
  if (item.equipSlot === "ground") return "accessory";
  if (item.equipable) return "equipable";
  return "artefact";
}

export const ITEM_TYPE_LABELS: Record<ItemType, string> = {
  skin: "Skin",
  sceneryCard: "Scenery",
  equipable: "Equipable",
  accessory: "Accessory",
  modifier: "Modifier",
  artefact: "Artefact",
};

/** A set is a named group of items whose `effect` describes what equipping
 * all of them together does — membership is purely by `itemIds`, not a
 * field on ItemDef, so adding an item to a set never touches its own entry. */
export interface ItemSet {
  id: string;
  /** Display name, e.g. "Prismatic". */
  name: string;
  /** What equipping the full set does — shown on each member's item preview. */
  effect: string;
  /** Item ids that make up this set. */
  itemIds: string[];
  /** Shared visual clue applied to every member's small card icon, on top of
   * whatever shape that item's own icon has — e.g. a rainbow gradient fill
   * instead of the item's usual solid dominant-colour tint, so set members
   * read as related regardless of their individual icon depiction. */
  visual?: { gradient: readonly string[] };
}

export const ITEM_SETS: ItemSet[] = [
  {
    id: "prismatic",
    name: "Prismatic",
    effect: "Even more rainbow",
    itemIds: ["rainbow-headband", "prism"],
    visual: { gradient: RAINBOW_RAMP },
  },
];

export function getItemSet(itemId: string): ItemSet | undefined {
  return ITEM_SETS.find((set) => set.itemIds.includes(itemId));
}

/** Whether every item in `set` is currently equipped. */
export function isSetFullyEquipped(
  equipped: Equipped | null | undefined,
  set: ItemSet,
): boolean {
  const ids = new Set(equippedItemIds(equipped));
  return set.itemIds.every((id) => ids.has(id));
}

/** Drives the inventory "Deck" slot row: one entry per visual group, in
 * left-to-right display order. `slots` is either the ordered list of
 * single-value EquippedSlot keys in the group (box i ↔ slots[i]), or the
 * literal "modifier" for the capped modifier array (box i ↔ equipped.modifier[i]).
 * `itemType` selects the icon + ITEM_TYPE_TEXT_CLASSES color for filled boxes. */
export interface DeckSlotGroup {
  label: string;
  itemType: ItemType;
  slots: EquippedSlot[] | "modifier";
  count: number;
}

export const DECK_SLOT_GROUPS: DeckSlotGroup[] = [
  {
    label: "Equipment",
    itemType: "equipable",
    slots: ["head", "face", "body"],
    count: 3,
  },
  {
    label: "Accessories",
    itemType: "accessory",
    slots: ["ground_left", "ground_right"],
    count: 2,
  },
  { label: "Scenery", itemType: "sceneryCard", slots: ["scenery"], count: 1 },
  {
    label: "Modifiers",
    itemType: "modifier",
    slots: "modifier",
    count: MAX_MODIFIERS,
  },
  { label: "Skin", itemType: "skin", slots: ["color"], count: 1 },
];

/** Total fixed slot capacity across all groups (3+2+1+6+1 = 13). */
export const DECK_TOTAL_SLOTS = DECK_SLOT_GROUPS.reduce(
  (sum, g) => sum + g.count,
  0,
);

export const RARITY_COLORS: Record<Rarity, string> = {
  common: "#9d9d9d",
  uncommon: "#1eff00",
  rare: "#0070dd",
  legendary: "#ff8000",
};

export const RARITY_LABELS: Record<Rarity, string> = {
  common: "Common",
  uncommon: "Uncommon",
  rare: "Rare",
  legendary: "Legendary",
};

/** Relative weight for random world drops — common is heaviest, legendary lightest. */
export const RARITY_DROP_WEIGHTS: Record<Rarity, number> = {
  common: 100,
  uncommon: 30,
  rare: 8,
  legendary: 1,
};

/** Items that can never appear as a random world drop, regardless of rarity. */
export const NON_DROPPABLE_ITEM_IDS = ["first-edition", "spirit-orb"] as const;

/** Listened minutes that earn one drop roll. Eligibility is a counter diff on
 * total_minutes_listened, not a wall-clock timer — see processSync step 5. */
export const DROP_TICK_MINUTES = 10;

/** Chance a drop is rolled on each eligible listening tick (see DROP_TICK_MINUTES).
 * 1 = guaranteed — every 10-minute tick drops something, with which item
 * decided by ITEM_DROP_WEIGHT_OVERRIDES / RARITY_DROP_WEIGHTS below. */
export const DROP_CHANCE_PER_TICK = 1;

/** Ceiling on how many owed rolls a single sync may award. The desktop path
 * never owes more than one (its minutes are capped per sync), but the Spotify
 * cron passes uncapped catch-up minutes and could otherwise owe dozens at
 * once. Anything above this carries over to the next sync rather than being
 * written off — see the drop_rolls_done bookkeeping in processSync. */
export const MAX_DROP_ROLLS_PER_SYNC = 20;

/** Per-item drop-weight overrides, applied instead of RARITY_DROP_WEIGHTS when
 * present. CDs are earned purely by listening (not by any special rarity),
 * so they're weighted well above even the heaviest common item to make them
 * the most likely drop by a wide margin. */
export const ITEM_DROP_WEIGHT_OVERRIDES: Partial<Record<string, number>> = {
  cd: 400,
};

/** Weighted-random pick from a rarity-tagged candidate pool. `rng` returns a
 * float in [0, 1) — inject Math.random in production, a seeded fn in tests. */
export function pickWeightedDrop<T extends { id: string; rarity: Rarity }>(
  candidates: T[],
  rng: () => number = Math.random,
): T | undefined {
  if (candidates.length === 0) return undefined;
  const weights = candidates.map(
    (c) => ITEM_DROP_WEIGHT_OVERRIDES[c.id] ?? RARITY_DROP_WEIGHTS[c.rarity],
  );
  const total = weights.reduce((a, b) => a + b, 0);
  let r = rng() * total;
  for (let i = 0; i < candidates.length; i++) {
    r -= weights[i];
    if (r <= 0) return candidates[i];
  }
  return candidates[candidates.length - 1];
}

// --- Constants ---
const SW = 30;
const SH = 18;
const CARD_HW = 0.85;
const CARD_HH = 1.3;
const TILT = 12 * (Math.PI / 180);
const CAM = 4.5;

const CORNERS: V3[] = [
  [-CARD_HW, -CARD_HH, 0],
  [CARD_HW, -CARD_HH, 0],
  [CARD_HW, CARD_HH, 0],
  [-CARD_HW, CARD_HH, 0],
];
const UVS: V2[] = [
  [0, 0],
  [1, 0],
  [1, 1],
  [0, 1],
];

// --- Card textures ---
function frontTexture(u: number, v: number): number {
  const bw = 0.055;
  if (u < bw || u > 1 - bw || v < bw || v > 1 - bw) return 0.9;
  const ib = 0.11,
    ibw = 0.012;
  if (
    (u > ib - ibw && u < ib + ibw && v > ib && v < 1 - ib) ||
    (u > 1 - ib - ibw && u < 1 - ib + ibw && v > ib && v < 1 - ib) ||
    (v > ib - ibw && v < ib + ibw && u > ib && u < 1 - ib) ||
    (v > 1 - ib - ibw && v < 1 - ib + ibw && u > ib && u < 1 - ib)
  )
    return 0.65;
  const diamonds: V2[] = [
    [0.16, 0.1],
    [0.84, 0.1],
    [0.16, 0.9],
    [0.84, 0.9],
  ];
  for (const [dx, dy] of diamonds) {
    const du = Math.abs(u - dx) / 0.035;
    const dv = Math.abs(v - dy) / 0.045;
    if (du + dv < 1) return 1.0;
  }
  const cx = 0.5,
    cy = 0.5;
  const blocks: [number, number, number, number][] = [
    [cx - 0.03, cy - 0.16, cx + 0.03, cy + 0.13],
    [cx - 0.08, cy - 0.13, cx - 0.02, cy - 0.09],
    [cx - 0.055, cy - 0.16, cx - 0.02, cy - 0.13],
    [cx - 0.09, cy + 0.13, cx + 0.09, cy + 0.17],
  ];
  for (const [x1, y1, x2, y2] of blocks) {
    if (u >= x1 && u <= x2 && v >= y1 && v <= y2) return 0.95;
  }
  return 0.3;
}

function backTexture(u: number, v: number): number {
  const bw = 0.055;
  if (u < bw || u > 1 - bw || v < bw || v > 1 - bw) return 0.7;
  const g = 0.065,
    w = 0.018;
  if (u % g < w || v % g < w) return 0.5;
  return 0.28;
}

function project(p: V3): V2 {
  const z = p[2] + CAM;
  const s = CAM / z;
  return [
    SW / 2 + p[0] * s * SW * 0.22 * CHAR_ASPECT,
    SH / 2 + p[1] * s * SH * 0.28,
  ];
}

function triUV(
  px: number,
  py: number,
  ax: number,
  ay: number,
  au: number,
  av: number,
  bx: number,
  by: number,
  bu: number,
  bv: number,
  cx: number,
  cy: number,
  cu: number,
  cv: number,
): V2 | null {
  const v0x = cx - ax,
    v0y = cy - ay,
    v1x = bx - ax,
    v1y = by - ay,
    v2x = px - ax,
    v2y = py - ay;
  const d00 = v0x * v0x + v0y * v0y,
    d01 = v0x * v1x + v0y * v1y,
    d02 = v0x * v2x + v0y * v2y,
    d11 = v1x * v1x + v1y * v1y,
    d12 = v1x * v2x + v1y * v2y;
  const den = d00 * d11 - d01 * d01;
  if (Math.abs(den) < 1e-10) return null;
  const inv = 1 / den;
  const s = (d11 * d02 - d01 * d12) * inv,
    t = (d00 * d12 - d01 * d02) * inv;
  if (s < -0.001 || t < -0.001 || s + t > 1.001) return null;
  const w = 1 - s - t;
  return [w * au + t * bu + s * cu, w * av + t * bv + s * cv];
}

function renderCardFrame(yAngle: number): string[] {
  const xf = CORNERS.map((v) => rotY(rotZ(v, TILT), yAngle));
  const e1: V3 = [
    xf[1][0] - xf[0][0],
    xf[1][1] - xf[0][1],
    xf[1][2] - xf[0][2],
  ];
  const e2: V3 = [
    xf[3][0] - xf[0][0],
    xf[3][1] - xf[0][1],
    xf[3][2] - xf[0][2],
  ];
  const faceN = normV(cross(e1, e2));
  const front = faceN[2] < 0;
  const diffuse = Math.abs(dot3(faceN, LIGHT));
  const pr = xf.map((v) => project(v));

  const bright: number[][] = Array.from({ length: SH }, () =>
    Array(SW).fill(-1),
  );
  const isContent: boolean[][] = Array.from({ length: SH }, () =>
    Array(SW).fill(false),
  );

  for (let sy = 0; sy < SH; sy++) {
    for (let sx = 0; sx < SW; sx++) {
      const px = sx + 0.5,
        py = sy + 0.5;
      const uv =
        triUV(
          px,
          py,
          pr[0][0],
          pr[0][1],
          UVS[0][0],
          UVS[0][1],
          pr[1][0],
          pr[1][1],
          UVS[1][0],
          UVS[1][1],
          pr[2][0],
          pr[2][1],
          UVS[2][0],
          UVS[2][1],
        ) ??
        triUV(
          px,
          py,
          pr[0][0],
          pr[0][1],
          UVS[0][0],
          UVS[0][1],
          pr[2][0],
          pr[2][1],
          UVS[2][0],
          UVS[2][1],
          pr[3][0],
          pr[3][1],
          UVS[3][0],
          UVS[3][1],
        );
      if (!uv) continue;
      let [u, v] = uv;
      if (!front) u = 1 - u;
      const tex = front ? frontTexture(u, v) : backTexture(u, v);
      const lit = tex * (0.2 + 0.8 * diffuse);
      bright[sy][sx] = lit;
      isContent[sy][sx] = front && tex > 0.5;
    }
  }

  return bright.map((row, y) =>
    row
      .map((val, x) => {
        if (val < 0) return " ";
        const idx = Math.min(
          Math.floor(val * (RAMP_ITEM.length - 1)),
          RAMP_ITEM.length - 1,
        );
        const ch = RAMP_ITEM[idx];
        if (ch === " ") return " ";
        return isContent[y][x]
          ? col("#FFD700", ch)
          : front
            ? col("#8B6914", ch)
            : col("#654A0E", ch);
      })
      .join(""),
  );
}

// --- Shared card-frame renderer for icon-based item cards ---
// Every non-signature item is presented as a card using the same
// CORNERS/UVS/TILT/CAM rig as First Edition and Prism above (untouched) —
// each item just supplies an icon glyph and a couple of accent colours
// instead of reimplementing the projection/lighting loop.

/** Icon-space radius so a circle centred on the card face reads as round
 * despite the card being taller than it is wide. */
const ICON_ASPECT = CARD_HH / CARD_HW;

function iconUV(u: number, v: number): V2 {
  return [u - 0.5, (v - 0.5) * ICON_ASPECT];
}

interface TexSample {
  bright: number;
  /** Present for "content" pixels — tints them instead of the card's dim colour. */
  color?: string;
}

/** Border, inner rule, and four corner diamonds shared by every icon card —
 * mirrors First Edition's frame proportions. Returns null over the open
 * interior so the caller's icon can fill it in. */
function cardChrome(u: number, v: number, accent: string): TexSample | null {
  const bw = 0.055;
  if (u < bw || u > 1 - bw || v < bw || v > 1 - bw) return { bright: 0.9 };
  const ib = 0.11,
    ibw = 0.012;
  if (
    (u > ib - ibw && u < ib + ibw && v > ib && v < 1 - ib) ||
    (u > 1 - ib - ibw && u < 1 - ib + ibw && v > ib && v < 1 - ib) ||
    (v > ib - ibw && v < ib + ibw && u > ib && u < 1 - ib) ||
    (v > 1 - ib - ibw && v < 1 - ib + ibw && u > ib && u < 1 - ib)
  )
    return { bright: 0.65 };
  const diamonds: V2[] = [
    [0.16, 0.1],
    [0.84, 0.1],
    [0.16, 0.9],
    [0.84, 0.9],
  ];
  for (const [dx, dy] of diamonds) {
    const du = Math.abs(u - dx) / 0.035;
    const dv = Math.abs(v - dy) / 0.045;
    if (du + dv < 1) return { bright: 1.0, color: accent };
  }
  return null;
}

function renderIconCard(
  yAngle: number,
  accent: string,
  dimColor: string,
  backColor: string,
  icon: (u: number, v: number) => TexSample | null,
): string[] {
  const xf = CORNERS.map((v) => rotY(rotZ(v, TILT), yAngle));
  const e1: V3 = [
    xf[1][0] - xf[0][0],
    xf[1][1] - xf[0][1],
    xf[1][2] - xf[0][2],
  ];
  const e2: V3 = [
    xf[3][0] - xf[0][0],
    xf[3][1] - xf[0][1],
    xf[3][2] - xf[0][2],
  ];
  const faceN = normV(cross(e1, e2));
  const front = faceN[2] < 0;
  const diffuse = Math.abs(dot3(faceN, LIGHT));
  const pr = xf.map((v) => project(v));

  const bright: number[][] = Array.from({ length: SH }, () =>
    Array(SW).fill(-1),
  );
  const pixelColor: (string | undefined)[][] = Array.from({ length: SH }, () =>
    Array(SW).fill(undefined),
  );

  for (let sy = 0; sy < SH; sy++) {
    for (let sx = 0; sx < SW; sx++) {
      const px = sx + 0.5,
        py = sy + 0.5;
      const uv =
        triUV(
          px,
          py,
          pr[0][0],
          pr[0][1],
          UVS[0][0],
          UVS[0][1],
          pr[1][0],
          pr[1][1],
          UVS[1][0],
          UVS[1][1],
          pr[2][0],
          pr[2][1],
          UVS[2][0],
          UVS[2][1],
        ) ??
        triUV(
          px,
          py,
          pr[0][0],
          pr[0][1],
          UVS[0][0],
          UVS[0][1],
          pr[2][0],
          pr[2][1],
          UVS[2][0],
          UVS[2][1],
          pr[3][0],
          pr[3][1],
          UVS[3][0],
          UVS[3][1],
        );
      if (!uv) continue;
      let [u, v] = uv;
      if (!front) u = 1 - u;
      let sample: TexSample;
      if (front) {
        sample = cardChrome(u, v, accent) ?? icon(u, v) ?? { bright: 0.3 };
      } else {
        const bw = 0.055;
        if (u < bw || u > 1 - bw || v < bw || v > 1 - bw) {
          sample = { bright: 0.7 };
        } else {
          const g = 0.065,
            w = 0.018;
          sample = { bright: u % g < w || v % g < w ? 0.5 : 0.28 };
        }
      }
      bright[sy][sx] = sample.bright * (0.2 + 0.8 * diffuse);
      pixelColor[sy][sx] = sample.color;
    }
  }

  return bright.map((row, y) =>
    row
      .map((val, x) => {
        if (val < 0) return " ";
        const idx = Math.min(
          Math.floor(val * (RAMP_ITEM.length - 1)),
          RAMP_ITEM.length - 1,
        );
        const ch = RAMP_ITEM[idx];
        if (ch === " ") return " ";
        const c = pixelColor[y][x];
        return col(c ?? (front ? dimColor : backColor), ch);
      })
      .join(""),
  );
}

// --- CD card ---
function cdCardIcon(u: number, v: number): TexSample | null {
  const [ix, iy] = iconUV(u, v);
  const r = Math.sqrt(ix * ix + iy * iy);
  const R = 0.27;
  if (r > R || r < R * 0.16) return null;
  const band = ((r / R) * 7) % 1;
  const bright = band < 0.5 ? 0.85 : 0.5;
  const color = r < R * 0.4 ? "#E8E8E8" : r < R * 0.7 ? "#C0C0C0" : "#808080";
  return { bright, color };
}

function renderCdFrame(yAngle: number): string[] {
  return renderIconCard(yAngle, "#C0C0C0", "#7a7a7a", "#4a4a4a", cdCardIcon);
}

// --- Spirit Orb card ---
function spiritOrbCardIcon(u: number, v: number): TexSample | null {
  const [ix, iy] = iconUV(u, v);
  const r = Math.sqrt(ix * ix + iy * iy);
  const R = 0.26;
  if (r > R) return null;
  const eyeR = R * 0.16;
  const ex = R * 0.32,
    ey = -R * 0.08;
  if (
    Math.hypot(ix - ex, iy - ey) < eyeR ||
    Math.hypot(ix + ex, iy - ey) < eyeR
  ) {
    return { bright: 0.15, color: "#1a1a2e" };
  }
  const shade = 0.9 - (r / R) * 0.35;
  return { bright: shade, color: "#d8c8ff" };
}

function renderSpiritOrbFrame(yAngle: number): string[] {
  return renderIconCard(
    yAngle,
    "#c9b8ff",
    "#7d6bb0",
    "#4a3d70",
    spiritOrbCardIcon,
  );
}

// --- Headphones card ---
function headbandArcIcon(
  u: number,
  v: number,
  cupColor: string | null,
): TexSample | null {
  const [ix, iy] = iconUV(u, v);
  const dist = Math.sqrt(ix * ix + iy * iy);
  const R = 0.26,
    bandT = 0.045;
  const angle = Math.atan2(iy, ix);
  const start = -2.7,
    end = -0.44; // upper arc, opening downward like a headband over ears
  if (Math.abs(dist - R) < bandT && angle > start && angle < end) {
    return { bright: 0.75, color: "#BBBBBB" };
  }
  if (cupColor) {
    for (const a of [start, end]) {
      const cx = R * Math.cos(a),
        cy = R * Math.sin(a);
      const d = Math.sqrt((ix - cx) ** 2 + (iy - cy) ** 2);
      if (d < 0.1) return { bright: d < 0.05 ? 0.9 : 0.6, color: cupColor };
    }
  }
  return null;
}

function renderHeadphonesFrame(yAngle: number): string[] {
  return renderIconCard(yAngle, "#c084fc", "#7a5aa0", "#4a3163", (u, v) =>
    headbandArcIcon(u, v, "#c084fc"),
  );
}

// --- Rainbow headband card ---
function rainbowHeadbandCardIcon(u: number, v: number): TexSample | null {
  const [ix, iy] = iconUV(u, v);
  const dist = Math.sqrt(ix * ix + iy * iy);
  const R = 0.26,
    bandT = 0.05;
  const angle = Math.atan2(iy, ix);
  const start = -2.7,
    end = -0.44;
  if (Math.abs(dist - R) < bandT && angle > start && angle < end) {
    const t = (angle - start) / (end - start);
    const idx = Math.min(
      RAINBOW_RAMP.length - 1,
      Math.floor(t * RAINBOW_RAMP.length),
    );
    return { bright: 0.85, color: RAINBOW_RAMP[idx] };
  }
  return null;
}

function renderRainbowHeadbandFrame(yAngle: number): string[] {
  return renderIconCard(
    yAngle,
    "#e8e2d0",
    "#8f8672",
    "#5c5648",
    rainbowHeadbandCardIcon,
  );
}

// --- Boombox card ---
function boomboxNoteIcon(u: number, v: number): TexSample | null {
  const [ix, iy] = iconUV(u, v);
  const headCx = -0.02,
    headCy = 0.22;
  const dHead = Math.sqrt((ix - headCx) ** 2 + (iy - headCy) ** 2);
  if (dHead < 0.16) return { bright: 0.85, color: "#f2f2f2" };
  const stemL = headCx + 0.12,
    stemR = headCx + 0.2;
  if (ix > stemL && ix < stemR && iy > -0.34 && iy < headCy)
    return { bright: 0.8, color: "#f2f2f2" };
  if (
    ix > stemR &&
    ix < stemR + 0.16 &&
    iy > -0.34 &&
    iy < -0.16 &&
    ix - stemR > (iy + 0.34) * 0.9
  )
    return { bright: 0.8, color: "#f2f2f2" };
  return null;
}

function renderBoomboxFrame(yAngle: number): string[] {
  return renderIconCard(
    yAngle,
    "#aeb4ba",
    "#75757a",
    "#45454a",
    boomboxNoteIcon,
  );
}

// --- Good Eye Sniper card ---
function goodEyeSniperIcon(u: number, v: number): TexSample | null {
  const [ix, iy] = iconUV(u, v);
  const r = Math.sqrt(ix * ix + iy * iy);
  const R = 0.27;
  if (r > R) return null;
  const ring = Math.floor((r / R) * 5); // 5 concentric bands, innermost = 0
  const isRed = ring % 2 === 0; // center + alternating bands red
  return {
    bright: isRed ? 0.8 : 0.95,
    color: isRed ? "#cc2222" : "#f2f2f2",
  };
}

function renderGoodEyeSniperFrame(yAngle: number): string[] {
  return renderIconCard(
    yAngle,
    "#e05050",
    "#8a3a3a",
    "#4a2020",
    goodEyeSniperIcon,
  );
}

// --- Generate all frames ---
// --- Prism (colour scheme) rendering ---

/** Scale a hex colour toward black — used for the card's reverse face. */
function shadeHex(hex: string, factor: number): string {
  const channel = (start: number) =>
    Math.min(
      255,
      Math.round(parseInt(hex.slice(start, start + 2), 16) * factor),
    )
      .toString(16)
      .padStart(2, "0");
  return `#${channel(1)}${channel(3)}${channel(5)}`.toUpperCase();
}

function prismTexture(u: number, v: number): number {
  const bw = 0.055;
  if (u < bw || u > 1 - bw || v < bw || v > 1 - bw) return 0.9;
  // Gentle sheen across the face so the gradient still reads as a lit card.
  return 0.55 + 0.35 * Math.sin((u + v) * Math.PI);
}

/** Band index for the diagonal colour sweep across the card face. */
function gradientBand(u: number, v: number, ramp: readonly string[]): number {
  const t = (u * 0.65 + v * 0.35) % 1;
  return Math.min(ramp.length - 1, Math.floor(t * ramp.length));
}

/** Diagonal gradient card shared by every equipable colour-scheme item —
 * Prism sweeps the rainbow, Poseidon's Gift sweeps the ocean ramp. */
function renderGradientCardFrame(
  yAngle: number,
  ramp: readonly string[],
): string[] {
  const xf = CORNERS.map((v) => rotY(rotZ(v, TILT), yAngle));
  const e1: V3 = [
    xf[1][0] - xf[0][0],
    xf[1][1] - xf[0][1],
    xf[1][2] - xf[0][2],
  ];
  const e2: V3 = [
    xf[3][0] - xf[0][0],
    xf[3][1] - xf[0][1],
    xf[3][2] - xf[0][2],
  ];
  const faceN = normV(cross(e1, e2));
  const front = faceN[2] < 0;
  const diffuse = Math.abs(dot3(faceN, LIGHT));
  const pr = xf.map((v) => project(v));

  const bright: number[][] = Array.from({ length: SH }, () =>
    Array(SW).fill(-1),
  );
  const bands: number[][] = Array.from({ length: SH }, () => Array(SW).fill(0));

  for (let sy = 0; sy < SH; sy++) {
    for (let sx = 0; sx < SW; sx++) {
      const px = sx + 0.5,
        py = sy + 0.5;
      const uv =
        triUV(
          px,
          py,
          pr[0][0],
          pr[0][1],
          UVS[0][0],
          UVS[0][1],
          pr[1][0],
          pr[1][1],
          UVS[1][0],
          UVS[1][1],
          pr[2][0],
          pr[2][1],
          UVS[2][0],
          UVS[2][1],
        ) ??
        triUV(
          px,
          py,
          pr[0][0],
          pr[0][1],
          UVS[0][0],
          UVS[0][1],
          pr[2][0],
          pr[2][1],
          UVS[2][0],
          UVS[2][1],
          pr[3][0],
          pr[3][1],
          UVS[3][0],
          UVS[3][1],
        );
      if (!uv) continue;
      let [u, v] = uv;
      if (!front) u = 1 - u;
      bright[sy][sx] = prismTexture(u, v) * (0.2 + 0.8 * diffuse);
      bands[sy][sx] = gradientBand(u, v, ramp);
    }
  }

  return bright.map((row, y) =>
    row
      .map((val, x) => {
        if (val < 0) return " ";
        const idx = Math.min(
          Math.floor(val * (RAMP_ITEM.length - 1)),
          RAMP_ITEM.length - 1,
        );
        const ch = RAMP_ITEM[idx];
        if (ch === " ") return " ";
        const hue = ramp[bands[y][x]];
        return col(front ? hue : shadeHex(hue, 0.45), ch);
      })
      .join(""),
  );
}

function renderPrismFrame(yAngle: number): string[] {
  return renderGradientCardFrame(yAngle, RAINBOW_RAMP);
}

function renderPoseidonsGiftFrame(yAngle: number): string[] {
  return renderGradientCardFrame(yAngle, OCEAN_RAMP);
}

function generateFrames(
  renderFn: (angle: number) => string[],
  count = 36,
): string[][] {
  // The card faces us for the yAngle arc (PI/2, 3*PI/2) — a symmetric 180°
  // window regardless of the cosmetic Z tilt. PI/2 itself is edge-on (zero
  // width, nothing to render), so start one frame step past it: the earliest
  // angle that's actually visible, keeping nearly the whole front-facing arc
  // ahead of frame 0.
  const step = (Math.PI * 2) / count;
  const start = Math.PI / 2 + step;
  return Array.from({ length: count }, (_, i) => renderFn(start + i * step));
}

const firstEditionFrames = generateFrames(renderCardFrame);
const cdFrames = generateFrames(renderCdFrame);
const headphonesFrames = generateFrames(renderHeadphonesFrame);
const rainbowHeadbandFrames = generateFrames(renderRainbowHeadbandFrame);
const boomboxFrames = generateFrames(renderBoomboxFrame);
const goodEyeSniperFrames = generateFrames(renderGoodEyeSniperFrame);
const prismFrames = generateFrames(renderPrismFrame);
const poseidonsGiftFrames = generateFrames(renderPoseidonsGiftFrame);
const spiritOrbFrames = generateFrames(renderSpiritOrbFrame);

// --- Clouds card ---
function cloudCardIcon(u: number, v: number): TexSample | null {
  const [ix, iy] = iconUV(u, v);
  const puffs: [number, number, number][] = [
    [-0.14, 0.02, 0.13],
    [0.05, -0.06, 0.17],
    [0.22, 0.04, 0.12],
  ];
  for (const [cx, cy, r] of puffs) {
    const d = Math.sqrt((ix - cx) ** 2 + (iy - cy) ** 2);
    if (d < r) return { bright: d < r * 0.6 ? 0.85 : 0.6, color: "#c7d3de" };
  }
  if (ix > -0.22 && ix < 0.3 && iy > 0.08 && iy < 0.16)
    return { bright: 0.6, color: "#c7d3de" };
  return null;
}

function renderCloudsFrame(yAngle: number): string[] {
  return renderIconCard(yAngle, "#8899aa", "#5f707d", "#3d4a56", cloudCardIcon);
}

const cloudsFrames = generateFrames(renderCloudsFrame);

// --- Stars card ---
function starCardIcon(u: number, v: number): TexSample | null {
  const [ix, iy] = iconUV(u, v);
  const dist = Math.sqrt(ix * ix + iy * iy);
  const outerR = 0.26,
    innerR = 0.1;
  const angle = Math.atan2(iy, ix) + Math.PI / 2;
  const seg = ((angle % (Math.PI * 2)) + Math.PI * 2) % (Math.PI * 2);
  const spike = seg / ((Math.PI * 2) / 5);
  const frac = spike - Math.floor(spike);
  const edgeR = innerR + (outerR - innerR) * (1 - Math.abs(frac - 0.5) * 2);
  if (dist < edgeR * 0.55) return { bright: 0.95, color: "#eaf2fb" };
  if (dist < edgeR) return { bright: 0.7, color: "#ccddee" };
  const sparkles: V2[] = [
    [-0.32, -0.3],
    [0.3, -0.28],
    [-0.28, 0.32],
  ];
  for (const [sx, sy] of sparkles) {
    const d = Math.sqrt((ix - sx) ** 2 + (iy - sy) ** 2);
    if (d < 0.03) return { bright: 0.8, color: "#8899aa" };
  }
  return null;
}

function renderStarsFrame(yAngle: number): string[] {
  return renderIconCard(yAngle, "#ccddee", "#5a6ea0", "#3a4868", starCardIcon);
}

const starsFrames = generateFrames(renderStarsFrame);

export const ITEMS: ItemDef[] = [
  {
    id: "first-edition",
    name: "First Edition Card",
    description: "A token of appreciation for early adopters.",
    rarity: "rare",
    frames: firstEditionFrames,
    // Artefacts (no equipSlot/equipable — see getItemType) are the only
    // stackable item type for now.
    stackable: true,
    sellPrice: 250,
  },
  {
    id: "cd",
    name: "Nostalgic Token",
    description:
      "An image of a CD on a dull card. Weird. Probably not worth much.",
    rarity: "common",
    frames: cdFrames,
    stackable: true,
    sellPrice: 10,
  },
  {
    id: "headphones",
    name: "Intimite Music Device",
    description: "Summons a pair of headphones on your herzie's head.",
    rarity: "uncommon",
    frames: headphonesFrames,
    equipable: true,
    equipSlot: "head",
    buyPrice: 8000,
    sellPrice: 100,
  },
  {
    id: "rainbow-headband",
    name: "Permanent Rainbow Dreams",
    description: "Rainbows forever on your mind. And head.",
    rarity: "uncommon",
    frames: rainbowHeadbandFrames,
    equipable: true,
    equipSlot: "head",
    buyPrice: 8000,
    sellPrice: 100,
  },
  {
    id: "boombox",
    name: "Box of Boom",
    description: "Grants your herzie real street cred.",
    rarity: "rare",
    frames: boomboxFrames,
    equipable: true,
    equipSlot: "ground",
    sellPrice: 250,
  },
  {
    id: "good-eye-sniper",
    name: "Good Eye, Sniper",
    description:
      "... and good ears! Displays your song hunt wins and boosts XP the more you rack up.",
    rarity: "rare",
    frames: goodEyeSniperFrames,
    equipable: true,
    equipSlot: "modifier",
    sellPrice: 250,
    modifier: { label: "Exp boost", tooltip: "2% per song hunt won" },
    // no buyPrice — reward-only, matches boombox
  },
  {
    id: "clouds",
    name: "Overcast",
    description: "Paints calming clouds on your herzie's sky.",
    rarity: "rare",
    frames: cloudsFrames,
    equipable: true,
    equipSlot: "scenery",
    sellPrice: 250,
  },
  {
    id: "stars",
    name: "Starfield",
    description: "Sprinkles a twinkling starfield on your herzie's sky.",
    rarity: "rare",
    frames: starsFrames,
    equipable: true,
    equipSlot: "scenery",
    sellPrice: 250,
  },
  {
    id: "prism",
    name: "Prismatic Surrenderer",
    description: "Turns your herzie into a walking rainbow.",
    rarity: "uncommon",
    frames: prismFrames,
    equipable: true,
    equipSlot: "color",
    sellPrice: 100,
  },
  {
    id: "poseidons-gift",
    name: "Poseidon's Gift",
    description:
      "Somehow ended up here. Use it only if you don't care about upsetting the gods.",
    rarity: "legendary",
    frames: poseidonsGiftFrames,
    equipable: true,
    equipSlot: "color",
    buyPrice: 100000,
    sellPrice: 500,
  },
  {
    id: "spirit-orb",
    name: "Greedy Spirit",
    description: "Tired of picking up items? This little guy can help.",
    rarity: "legendary",
    frames: spiritOrbFrames,
    equipable: true,
    equipSlot: "ground",
    buyPrice: 50000,
    sellPrice: 500,
  },
];

export function getItem(id: string): ItemDef | undefined {
  return ITEMS.find((item) => item.id === id);
}

// getItemColor lived here. It moved to item-canvas.ts — the module its three
// dependencies already come from — so that this file stays free of the
// rendering chain (item-canvas -> creature-renderer, which pulls in canvas
// types). That keeps items.ts isomorphic and lets it be shared verbatim with
// the Deno edge functions via game-rules.ts. It is still re-exported from the
// package root, so importers are unaffected.

/** Filters raw {id, rarity} rows (e.g. fetched from the `items` DB table) down
 * to ones that are both a known catalog item and have a rarity recognized by
 * RARITY_DROP_WEIGHTS. Defends pickWeightedDrop against an id absent from
 * this catalog (mid-migration, a rename that left the old row behind, an
 * admin-created row) or a bad rarity value — either would otherwise let a
 * drop roll onto something the client can never render or collect, which
 * (since a pending drop is never overwritten) would silently and permanently
 * block that user from ever getting another drop. */
export function filterDroppablePool<T extends { id: string; rarity: string }>(
  rows: T[],
): (T & { rarity: Rarity })[] {
  return rows.filter(
    (r): r is T & { rarity: Rarity } =>
      getItem(r.id) !== undefined && r.rarity in RARITY_DROP_WEIGHTS,
  );
}
