// @generated by scripts/vendor-shared.mjs — DO NOT EDIT.
// Source: packages/shared/src/leveling.ts
// Run `pnpm vendor:shared` after changing the original.

import type { ActiveMultiplier, Herzie, Stage } from "./types.ts";

export function xpForLevel(level: number): number {
  return Math.floor(100 * level ** 1.5);
}

export function totalXpForLevel(level: number): number {
  let total = 0;
  for (let i = 2; i <= level; i++) {
    total += xpForLevel(i);
  }
  return total;
}

export function xpToNextLevel(herzie: Herzie): number {
  const needed = xpForLevel(herzie.level + 1);
  const progressInLevel = herzie.xp - totalXpForLevel(herzie.level);
  return needed - progressInLevel;
}

export function levelProgress(herzie: Herzie): number {
  const needed = xpForLevel(herzie.level + 1);
  const progressInLevel = herzie.xp - totalXpForLevel(herzie.level);
  return Math.min(1, Math.max(0, progressInLevel / needed));
}

export function stageForLevel(level: number): Stage {
  if (level >= 25) return 3;
  if (level >= 10) return 2;
  return 1;
}

const BASE_XP_PER_MINUTE = 10;

/**
 * Calculate XP gained for a listening period.
 * Multipliers are always provided by the server (or loaded from cache).
 */
export function calculateXpGain(
  minutes: number,
  multipliers: ActiveMultiplier[],
): number {
  let xp = minutes * BASE_XP_PER_MINUTE;
  if (multipliers.length > 0) {
    const totalBonus = multipliers.reduce((sum, m) => sum + m.bonus, 0);
    xp *= 1 + totalBonus;
  }
  return xp;
}

/** One built-in XP bonus's formula, tunable from the dev admin
 * (public.xp_bonuses, 00091). `amount` is the flat bonus (boost), or the
 * bonus per streak day / per song hunt won; `cap` bounds the total. */
export type XpBonusRule = {
  enabled: boolean;
  amount: number;
  cap: number | null;
};

export type XpBonusId = "boost" | "streak" | "good_eye_sniper";
export type XpBonusConfig = Record<XpBonusId, XpBonusRule>;

/** What the game used before these became editable — and still uses when
 * the database doesn't send them (a sync_context predating 00091). */
export const DEFAULT_XP_BONUSES: XpBonusConfig = {
  boost: { enabled: true, amount: 10.0, cap: null },
  streak: { enabled: true, amount: 0.01, cap: null },
  good_eye_sniper: { enabled: true, amount: 0.02, cap: 0.3 },
};

/** Builds the config from sync_context's `xp_bonuses` rows, falling back to
 * the defaults for anything missing or malformed. */
export function xpBonusConfig(
  rows:
    | readonly {
        id: string;
        enabled: boolean;
        amount: number;
        cap: number | null;
      }[]
    | undefined,
): XpBonusConfig {
  const config = { ...DEFAULT_XP_BONUSES };
  for (const row of rows ?? []) {
    if (!(row.id in config) || !(row.amount > 0)) continue;
    config[row.id as XpBonusId] = {
      enabled: row.enabled,
      amount: row.amount,
      cap: row.cap != null && row.cap > 0 ? row.cap : null,
    };
  }
  return config;
}

/** `count` units of a per-unit bonus (streak days, hunts won), capped; 0
 * when the bonus is off. */
export function scaledBonus(rule: XpBonusRule, count: number): number {
  if (!rule.enabled || count <= 0) return 0;
  const bonus = count * rule.amount;
  return rule.cap == null ? bonus : Math.min(bonus, rule.cap);
}

/** Good Eye Sniper's bonus for this many song hunts won: by default +2% per
 * win, capped at +30% (15 wins). */
export function goodEyeSniperBonus(
  songHuntWins: number,
  rule: XpBonusRule = DEFAULT_XP_BONUSES.good_eye_sniper,
): number {
  return scaledBonus(rule, songHuntWins);
}

export function applyXp(
  herzie: Herzie,
  xpGain: number,
): { leveledUp: boolean; evolved: boolean; newStage?: Stage } {
  herzie.xp += xpGain;
  let leveledUp = false;
  let evolved = false;
  let newStage: Stage | undefined;
  while (herzie.xp >= totalXpForLevel(herzie.level + 1)) {
    herzie.level++;
    leveledUp = true;
    const stage = stageForLevel(herzie.level);
    if (stage !== herzie.stage) {
      herzie.stage = stage;
      evolved = true;
      newStage = stage;
    }
  }
  return { leveledUp, evolved, newStage };
}
