/**
 * Types and helpers shared by the admin panels. Lives apart from GameAdmin so
 * the panels can import it without a cycle back into the page component.
 */

export const INPUT =
  "w-full bg-bg border border-border rounded-sm px-3 py-2 text-sm focus:outline-none focus:border-purple";

export type CatalogItem = {
  id: string;
  name: string;
  description: string;
  rarity: string;
  sell_price?: number | null;
  stackable?: boolean | null;
  equipable?: boolean | null;
  equip_slot?: string | null;
};

export type AdminEvent = {
  id: string;
  type: string;
  title: string;
  description: string | null;
  active: boolean;
  starts_at: string;
  ends_at: string;
  config: Record<string, unknown>;
  created_at: string;
  /** Set on occurrences generated by a recurring series (00081). */
  series_id?: string | null;
  occurrence_at?: string | null;
  skipped?: boolean;
  customized?: boolean;
  /** A curator's proposal, held back until the admin approves it. */
  needs_approval?: boolean;
  /** Live HP, present on boss_fight events only. */
  boss?: { hp: number; maxHp: number; killed: boolean; escaped: boolean };
};

export type EventSeries = {
  id: string;
  type: "song_hunt" | "boss_fight" | "merchant";
  title: string;
  description: string | null;
  enabled: boolean;
  anchor_at: string;
  interval_days: number;
  duration_minutes: number;
  until: string | null;
  config_template: Record<string, unknown>;
};

export type EventStatus =
  | "running"
  | "scheduled"
  | "needs setup"
  | "awaiting approval"
  | "skipped"
  | "ended"
  | "inactive";

export function getEventStatus(event: AdminEvent, now: Date): EventStatus {
  const start = new Date(event.starts_at);
  const end = new Date(event.ends_at);
  if (event.skipped) return "skipped";
  if (!event.active) {
    // A series occurrence that is off without being skipped is a draft the
    // server is holding back until it has a track / stock.
    if (event.series_id && now <= end) {
      return event.needs_approval ? "awaiting approval" : "needs setup";
    }
    return "inactive";
  }
  if (now < start) return "scheduled";
  if (now > end) return "ended";
  return "running";
}

export const STATUS_STYLES: Record<EventStatus, string> = {
  running: "text-green",
  scheduled: "text-yellow",
  "needs setup": "text-purple",
  "awaiting approval": "text-orange",
  skipped: "text-text-dim line-through",
  ended: "text-text-dim",
  inactive: "text-red",
};

export const EVENT_TYPE_LABELS: Record<string, string> = {
  song_hunt: "Orphiez (song hunt)",
  boss_fight: "boss fight",
  merchant: "Good ol' George",
  secret_track: "secret track",
};

/** Text + tinted background per event type, for calendar chips and tags. */
export const EVENT_TYPE_STYLES: Record<string, string> = {
  song_hunt: "border-cyan text-cyan bg-cyan/10",
  boss_fight: "border-red text-red bg-red/10",
  merchant: "border-yellow text-yellow bg-yellow/10",
  secret_track: "border-purple text-purple bg-purple/10",
};

/** Format for native `<input type="datetime-local">` values (local wall clock). */
export function toDatetimeLocalValue(date: Date): string {
  if (Number.isNaN(date.getTime())) return "";
  const pad = (n: number) => String(n).padStart(2, "0");
  return `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())}T${pad(date.getHours())}:${pad(date.getMinutes())}`;
}

export function isoToDatetimeLocal(iso: string): string {
  return toDatetimeLocalValue(new Date(iso));
}

/** Convert a datetime-local string to ISO for the API. */
export function datetimeLocalToIso(value: string): string {
  const d = new Date(value);
  if (Number.isNaN(d.getTime())) return value;
  return d.toISOString();
}

/** "3d 4h", "5h 12m", "8m" — coarse, for countdowns. */
export function formatDuration(ms: number): string {
  const minutes = Math.max(0, Math.round(ms / 60_000));
  const d = Math.floor(minutes / 1440);
  const h = Math.floor((minutes % 1440) / 60);
  const m = minutes % 60;
  if (d > 0) return h > 0 ? `${d}d ${h}h` : `${d}d`;
  if (h > 0) return m > 0 ? `${h}h ${m}m` : `${h}h`;
  return `${m}m`;
}

export async function adminFetch<T>(
  path: string,
  secret: string,
  init?: RequestInit,
): Promise<T> {
  const res = await fetch(path, {
    ...init,
    headers: {
      "Content-Type": "application/json",
      "x-admin-secret": secret,
      ...init?.headers,
    },
  });
  const body = await res.json().catch(() => ({}));
  if (!res.ok) {
    throw new Error(
      (body as { error?: string }).error ?? `Request failed (${res.status})`,
    );
  }
  return body as T;
}
